# Generated by Django 4.0.2 on 2022-02-26 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetch_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeholder',
            name='item_id',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
