# Generated by Django 3.2.12 on 2022-02-26 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetch_api', '0002_placeholder_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeholder',
            name='thumbnail_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
