# Generated by Django 3.2.12 on 2022-02-26 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetch_api', '0003_alter_placeholder_thumbnail_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeholder',
            name='albumId',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
