# Generated by Django 3.2.12 on 2022-02-26 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetch_api', '0004_placeholder_albumid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeholder',
            name='albumId',
            field=models.IntegerField(),
        ),
    ]
