# Generated by Django 3.2.12 on 2022-03-05 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fetch_api', '0005_alter_placeholder_albumid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlaceHolder',
        ),
    ]
